default_config:
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.2.97:3218/
    require_admin: true

wake_on_lan: # enables `wake_on_lan` integration

automation:
  - alias: "Turn On Living Room TV with WakeOnLan"
    trigger:
      - platform: webostv.turn_on
        entity_id: media_player.lg_webos_smart_tv
    action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: aa:bb:cc:dd:ee:ff