default_config:
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.2.97:3218/
    require_admin: true
    
# enables `wake_on_lan` integration
wake_on_lan: 
